add: set -e for workflow failure

diff --git a/.github/workflows/build-test.yml b/.github/workflows/build-test.yml
--- a/.github/workflows/build-test.yml
+++ b/.github/workflows/build-test.yml
@@ -38,9 +38,11 @@ jobs:
                 echo OLLAMA_IP = ${{ secrets.OLLAMA_IP }} >> .env
                 echo OLLAMA_PORT = ${{ secrets.OLLAMA_PORT }} >> .env
                 echo ADMINS = ${{ secrets.ADMINS }} >> .env
-
+              
+              # set -e ensures if nohup fails, this section fails
             - name: Startup Discord Bot Client
               run: |
+                set -e
                 nohup npm run prod &
 
     Discord-Ollama-Container-Build: # test docker build and run
